- mysite/profile/templates/profile/info_wrapper.html
changed "How to contact me" user interface instruction : "text area below"
> fix issue 1500 - "How to contact me" update user interface instruction

- docs/getting_started/handling_contributions.rst
https://github.com/openhatch/oh-mainline/issues/1306
> Add note on timeboundedness of working on PRs

- docs/advanced/developer_notes.rst
- docs/advanced/index.rst
- docs/getting_started/index.rst
- docs/getting_started/key_features_openhatch_site.rst
- docs/index.rst
After the January development meeting, this PR documents short-term developer notes,
> Add doc for developer notes

- docs/getting_started/index.rst
- docs/getting_started/key_features_openhatch_site.rst
- docs/index.rst
Doc added to Getting Started section on the key features and goals of the OpenHatch website. The hope is that this doc will give developers and contributors guidance on the project.
> Add doc on key features and goals

- mysite/base/templates/meta.html
- mysite/base/views.py
- mysite/profile/admin.py
- mysite/profile/migrations/0098_auto__del_dataimportattempt__del_field_citation_data_import_attempt__d.py
- mysite/profile/models.py
- mysite/profile/tasks/__init__.py
- mysite/profile/tests.py
- mysite/profile/views.py
- mysite/static/js/importer.js
- mysite/static/js/profile/editor/tests.js
- mysite/urls.py
Resolves https://github.com/openhatch/oh-mainline/issues/1458 
Please review, @paulproteus!
> Remove dataimport

- mysite/base/tests.py
- mysite/base/views.py
- mysite/profile/tasks/__init__.py
- mysite/profile/views.py
- mysite/static/js/importer.js
Removes a few references to DIAs left in code after PR #1508.
> Remove remaining dia references

- mysite/search/migrations/0053_make_project_name_really_unique.py
Remove data import attempt from migration. The migration causing an error. The forwards code was removed (@paulproteus, @ehashman) please double check that the SQL statement is not needed. Thanks.
> Remove data import from migration and remove forward db action

- docs/community/contact.rst
> Update contact.rst for clarity

- docs/advanced/advanced_installation.rst
Making the names of files and links more visible in the paragraph.
> Issue  #1565 Bolding names of files or updates

- .travis.yml
- mysite/base/depends.py
- mysite/base/tests.py
- mysite/customs/tests.py
- mysite/profile/management/commands/send_emails.py
- mysite/profile/models.py
- mysite/profile/views.py
- mysite/search/view_helpers.py
- mysite/settings.py
Clean up logging formats and settings to help log messages be more useful during debugging.
> Fix mysql testing and fixture loading for local testing and Travis CI

- mysite/project/views.py
This PR cleans up the logging in `mysite/project/views.py` and the return statement for `edit_project`.
The local user testing does not cause an error on redirect.
> Fix edit_project to redirect properly #1541

- mysite/settings.py
Changed DEBUG=False to DEBUG=True in settings.py
> Fixes #1576

- docs/internals/index.rst
- docs/internals/security.rst
Includes provisions for what OpenHatch does and does not prioritize.
/cc @paulproteus
> Add a Security policy file to the docs.

- mysite/account/templates/account/signup.html
- mysite/account/tests.py
- mysite/account/views.py
redirect user to original page that brought them to signup page or if they sign up from homepage, go to their profile
> Issue-819 Redirect user after sign up

- mysite/base/templates/base/base.html
- mysite/static/less/base/base.less
Fixes: #1437
I've made a PR for a contributor after doing a rebase.
> Makes the footer stick to the bottom of the page.

- mysite/search/tests.py
- mysite/search/view_helpers.py
> Correct typo. Fixes Issue #1592

- mysite/account/templates/account/login.html
- mysite/account/templates/account/login_old.html
- mysite/static/css/account/auth.css
*Also remove bolding so that it's not confusing
*Solves? issue #451 IMO at least
Before
After
Before
After
> Move in-line style to stylesheet

- docs/getting_started/getting_started.rst
Started a Getting Unstuck section in Getting Started documention, on tips about doing searches.
Hopefully closes #1580
> Getting Unstuck section

- mysite/static/less/base/base.less
*Fixes #1599
*If anyone can test this to make sure it works, or explain why it works to me, that would be great
> Remove bottom specification for footer

- mysite/missions/templates/missions/shell/ls.html
change ls -a to ls -l in the section about the -l option
> change ls -a to ls -l

- docs/conf.py
- docs/getting_started/documentation.rst
- docs/getting_started/installation.rst
This is a straight-forward PR for any newcomers to review and confirm.
> Fix formatting in getting started docs with notes

- mysite/base/management/commands/nagios.py
- mysite/base/tests.py
- mysite/bugsets/tests.py
- mysite/customs/core_bugimporters.py
- mysite/search/fixtures/bugs-for-two-projects.json
- mysite/search/tests.py
This is still a work in process but slowly chipping away at getting the tests running properly.
> Fix search test and mark remaining MySQL failures/errors as expectedFailures

- docs/tutorials/add_user_project.rst
- mysite/profile/templates/profile/importer.html
@shriyanka, let me know if you'd like me to change anything!
> Rewritten commits to help with git issues for PR #1555, closes #1550

- mysite/missions/templates/missions/pipvirtualenv/setup.html
> Recommend modifying .bashrc in pipvirtualenv/setup.html

- CONTRIBUTING.md
Covers #1560 and includes changes from @shaunagm
> Added CONNTRIBUTING.md

- docs/tutorials/add_user_project.rst
Made necessary changes and reviews.
> Issue #1622 Review "Adding a User and Project" docs for grammar and capitalization

- mysite/base/templates/base/answer-in-feed.html
Alt tags for profile pictures and default profile pics
> add alt tags to profile pictures

- mysite/scripts/snapshot_then_push.sh
Resolves https://github.com/openhatch/oh-mainline/issues/1534. Never tested this on a real prod server, because I have no access to it. Please do review! When reviewing this, let me know how I can make this bash script more safe and fool-proof. I do not know of any unit tests that are able to test bash scripts.
> Rsync the snapshot db with prod OH server

- mysite/base/templates/base/answer-in-feed.html
- mysite/base/templates/base/index.html
- mysite/base/templates/base/wannahelp-in-feed.html
Closes #1446. This PR adds alt text to the image of our mascot on our homepage. And also adds alt text to the image in [this file] (https://github.com/openhatch/oh-mainline/blob/master/mysite/base/templates/base/wannahelp-in-feed.html), which was not addressed by #1638. :-)
Please let me know if this needs further work. I would love to work on it!
Thanks & regards,
Eeshan Garg
> Add ALT text to images on homepage

- mysite/static/css/project/project.css
- mysite/static/less/base/base.less
Hi All,
This fixes the issue https://github.com/openhatch/oh-mainline/issues/1621.
Thanks,
Sunil
> Fixed the alignment of 'Subscribe' button

- mysite/missions/svn/views.py
Fix issue #1648.
Remove unneeded code.
> Remove line that is unnecessary - issue #1648

- mysite/base/depends.py
- mysite/missions/management/commands/svn_precommit.py
- mysite/missions/svn/forms.py
- mysite/missions/svn/view_helpers.py
- mysite/missions/svn/views.py
Most of this PR is additional comments and formatting changes (mostly for readability and some violate pep8 line length). The mission works properly locally.
> Refactor SVN mission to fix 500 errors Issue #1398

- .travis.yml
- README.rst
This is an initial PR to add codecov service to oh-mainline.
> Add codecov

- README.rst
Update coveralls badge using code snippet from coveralls
> Update coveralls badge

- mysite/missions/templates/missions/diffpatch/recursive_diff.html
- mysite/missions/templates/missions/diffpatch/recursive_patch.html
- mysite/missions/templates/missions/diffpatch/single_file_diff.html
- mysite/missions/templates/missions/diffpatch/single_file_patch.html
This fixes the issues with the diff missions and addresses: https://github.com/openhatch/oh-mainline/issues/1694
> Fix docs in diff mission

- .travis.yml
- README.rst
- mysite/account/forms.py
- mysite/account/tests.py
- mysite/missions/base/tests.py
- mysite/missions/svn/tests.py
- mysite/missions/tests.py
- mysite/testrunner.py
Remove sudo from Travis.yml so that Travis will build more quickly.
Clean up mission tests. Add some docstrings and reorder imports.
Adjust testrunner settings to cut down on some of the extraneous output to the Terminal when running tests.
> Update travis config, reorg imports, add docstrings for tests

- README.rst
Seemed like a good idea
https://github.com/openhatch/oh-mainline/issues/1717
> Link to docs in readme

- docs/index.rst
Adding captions to sidebar menu to improve readability by making visual sections
> Adding captions to sidebar menu

- README.rst
Addresses https://github.com/openhatch/oh-mainline/issues/1730
> Add Read the docs badge to README

- mysite/missions/git/models.py
> Remove unneeded git mission models.py file

- mysite/static/js/importer.js
Addresses https://github.com/openhatch/oh-mainline/issues/1582.
> Add client side validation for project name field in profile importer.js

- README.rst
> Added link to Freenode webchat

- docs/getting_started/getting_started.rst
this should now point to the open issues in the github repository that are marked as bitesize.
> fix open easy issues link

- mysite/missions/templates/missions/git/about_git.html
> Updating the style of input to fix issue #1572

- mysite/base/depends.py
- mysite/base/tests.py
- mysite/profile/tests.py
Addresses #1711 for profile submodule.
Edits to profile tests and depends.py
> Edit, document, and review profile tests #1711

- mysite/profile/models.py
@ehashman This is the second half of the split of PR #1725. This includes changes to the models.
The significant changes were:
1. Reorder imports and check that they were being used
2. Relax line length to 99 characters
3. Update some docstrings
4. Rebreak some long lines for easier comprehension
> Clean up profile/models.py (Split from PR #1725)

- mysite/missions/templates/missions/shell/ls.html
This might fix https://github.com/openhatch/oh-mainline/issues/1752
> man ls for OS X bash added

- docs/community/contact.rst
> add link to https://botbot.me/irc-guide/ in IRC help docs

- README.rst
based on:
http://lists.openhatch.org/pipermail/devel/2015-December/003872.html
> update README, add section detailing future plans
