openhatch/oh-mainline

mysite/static/less/base/base.less
mysite/static/less/base/landing.less

This partially reverts 98331703bc6cf5ecec711575a5e44c5f39b8d51e
Close #1512
(Note that I could only reproduce #1512 in Firefox, not in
Chromium.)

Move front-page-specific CSS rules to landing.less

---

docs/getting_started/handling_contributions.rst
docs/internals/continuous_integration.rst

This Pull Request updates the Travis CI and Continuous Integration docs. Testing Basics documentation updated for consistency.
Updates Continuous Integration to refer to the very well done overview of CI here: http://www.aosabook.org/en/integration.html 
This addresses issue #1428.

Update docs on Continuous Integration #1428

---

mysite/base/decorators.py
mysite/base/view_helpers.py
mysite/base/views.py
mysite/customs/management/commands/import_bugimporter_data.py
mysite/missions/base/views.py
mysite/missions/svn/views.py
mysite/profile/view_helpers.py
mysite/profile/views.py
mysite/search/tests.py
mysite/search/views.py

Remove remaining simplejson references in the files of the mysite directory. simplejson was deprecated in Django 1.5. The Python json module should be used going forward.
https://docs.djangoproject.com/en/1.7/releases/1.5/#django-utils-simplejson

Remove remaining simplejson (deprecated) references

---

docs/getting_started/testing_basics.rst

Added a new section in "Testing Basics" titled, "Controlling detail of test output" and specified the use of  `--verbosity`/  `-v` to get  more descriptive output.

added a new section to basic testing documentation #1479

---

mysite/base/templates/base/base.html

Earlier 'Intro to developers' link (http://openhatch.readthedocs.org/en/latest/README.html) was showing 404 error. The link actually should be 'http://openhatch.readthedocs.org/en/latest'. Made changes.

'Intro to developers' link was broken. Repaired!

---

docs/getting_started/project_overview.rst

The 'Other ways to contact us' was taking me to http://openhatch.readthedocs.org/en/latest/contributor/contact.html which gives a 404 error. The actual link is http://openhatch.readthedocs.org/en/latest/community/contact.html . Updated.

Link to 'Other ways to contact us' was broken. Repaired

---

mysite/testrunner.py

As per the last comment on #1392, the OpenHatchXMLTestRunner has been removed from mysite.test module. No existing tests have failed. Also, the current documentation makes no mention of xml test reporting therefore requiring no changes.

Remove OpenHatchXMLTestRunner as a fix for #1392

---

mysite/customs/tests.py
mysite/search/migrations/0014_populate_icons_for_existing_projects_LATER.py
mysite/search/models.py

fix for #1524 
Do recommend changes if required.

remove populate_icon_from_ohloh

---

mysite/base/templates/base/answer-in-feed.html
mysite/base/templates/base/wannahelp-in-feed.html

See: <https://github.com/openhatch/oh-mainline/issues/1446>
As mentioned in the issue above, much of the ALT portion had already been resolved by another PR earlier. About the redundant links, @paulproteus suggested that if possible, none of the links should be removed and also said something about specifying alt="" to fix this. However, if I'm not mistaken, I think specifying alt="" to fix this will work only if an image and some adjacent text link to the same page, not in the case where some text links to a page and some adjacent text links to that same page; so what should I do about redundant links like these?
Also, the only section of the homepage that needed some work was the "Recent site activity" section. The images of the users had no alt text and the image and adjacent text (the …

Add ALT text to images on homepage

---

mysite/base/templates/base/donate.html

Browser support for this fix is approximately 88%. For those donating,
using invalid text, on IE8/IE9/Opera Mini the current behavior will
persist (PayPal error)

Fix for #1581, donation allows invalid text

---

mysite/settings.py

As mentioned [here](https://github.com/openhatch/oh-mainline/pull/1551#issue-60255135), the application would throw a 500 error for requests to `robots.txt` when running on localhost with `DEBUG=False`

Fix robots.txt with DEBUG=False on localhost

---

mysite/bugsets/templates/edit_index.html
mysite/bugsets/views.py
mysite/static/css/project/project.css

Hi @paulproteus @ehashman @willingc @shaunagm,
I have added a link in the 'Edit a bugset' page to include a navigation link back to its list view of the set. Below screenshot shows my change.
Please go through the code and let me know if I need to make any changes to the code.
This fixes the issue - https://github.com/openhatch/oh-mainline/issues/1385
Thanks,
Sunil

Added a link in the 'Edit a Bug Set' page 

---

mysite/profile/forms.py

as it was confusing to see a real nickname there.  Firefox on Windows shows placeholders in a not-very-pale grey, so it wasn't obvious that it was a placeholder.

Change the IRC Nickname placeholder from ArcTanSusan to your_irc_nick

---

mysite/profile/migrations/0090_add_location_table.py

Remove unnecessary db settings that prevents Django from completing the mysql migration.
Needed step to address #1204

Remove unneeded MySQL settings from migration

---

mysite/config-files/crontab.linode

Bug: django_session and sessionprofile_sessionprofile tables aren't
pruned.
Solution: The crontab will do clearsessions daily.
Resolves https://github.com/openhatch/oh-mainline/issues/1591

Add a daily clearsessions crontab to prod server

---

.travis.yml

Closes #1618 
Updated Travis' configuration to remove MySQL fro allowed failures.

Remove MySQL as an allowed failure in Travis - Closes #1618

---

mysite/base/tests.py

- This should fix those tests failing due to differences between \n and
\r\n
- update docstring to improve traceback messages
This should partially address #1601

Fix file opener for universal ending

---

mysite/base/templates/base/events.html

Hi @shaunagm @ehashman 
I have rearranged the 'Boston Python Workshop' and 'OSCTC' nodes in the events page.
This fixes https://github.com/openhatch/oh-mainline/issues/1602. 
Please review the changes and let me know if any more changes are required.
Thanks,
Sunil

Rearranged Boston Python Workshop and OSCTC nodes in the events page

---

mysite/account/templates/account/edit_photo.html
mysite/account/views.py
mysite/static/css/account/settings.css
mysite/static/js/account/edit_photo.js

Hi @paulproteus @ehashman  @willingc @shaunagm ,
I've modified the "Edit your Profile Image" flow to use AJAX; The progress is reported in a callback in which the progress bar is updated. Here's what it looks like:
I've removed the HttpResponseRedirect in the edit_photo_do view and have instead returned a plain text message. The notification pops up on completion of the upload:
I've tested it on the versions of Chrome and Firefox I use and it seems to work fine. Please do let me know what you think, and if you want the color/position of the progress bar to be changed in any way. While testing these changes locally, please do use an image of about 3-4 MB :)
This resolves Issue #560.
Thanks :)

Use AJAX for image upload and show a progess bar: Issue #560

---

mysite/static/less/base/base.less

The footer on the blog currently covers the top of the page, because it has absolute positioning.
This PR just gets rid of the absolute positioning.

fix footer position issue on blog

---

mysite/customs/management/commands/import_bugimporter_data.py
mysite/customs/tests.py

This addresses one fraction of the "bug import isn't working" problem.
The particular crash that some bugs are triggering is that their `description` field is `null`, and this disagrees with our data types.
This works around that by not causing that to absolutely break the bug import process.

In the case of a crash during bug import, keep going

---

mysite/static/css/account/settings.css

Seems removing the margin-bottom and setting the padding to 0 fixed the issue.
Here is Chrome in Yosemite 10.10.3
and Safari
and Firefox

Removed margin-bottom and set padding to 0

---

mysite/missions/svn/tests.py
mysite/missions/svn/views.py

Removed a try block and un-pep8ed view file for svn mission. The diff step of the mission now redirected properly on my local system. It is not throwing a 500 error locally.

Correct svn mission's diff step to remove 500 error [Issue #1399]

---

mysite/base/templates/base/base.html

Remove redundant 'Code docs' link to the OpenHatch docs on homepage

---

mysite/missions/templates/missions/pipvirtualenv/setup.html

Fixes #1653. :-)
Hi!
The use of the ```<kbd></kbd``` tag (I checked and this tag is available in all mainstream HTML versions) here in this PR instead of the usual ```<pre></pre>``` tag is deliberate as the commands (when wrapped in ```<pre></pre>```) were too long for the HTML ```<div>``` container that surrounds the area where the installation instructions are displayed. :-) The use of the ```<kbd></kbd>``` tag is semantically correct as well since this tag is wrapped around keyboard input intended to be typed by the user/visitor.
If this PR needs further work, I would love to work on it!
Thanks & regards,
Eeshan Garg

Recommend distro specific commands in the pipvirtualenv mission

---

run_importer.sh

Massive props to @pdurbin for noticing this.
Probably the best next step is to rewrite this in Python.

Use valid shell syntax in run_importer.sh

---

mysite/search/templates/search/result.html
mysite/static/js/search/search.js

When selecting "expand" on a bug, the link text will become "collapse" and vice-versa. It will also swap them when selecting "expand all"/"collapse all". (Issue #1536)

Swap expand/collapse when a bug is expanded/collapsed - issue #1536

---

mysite/missions/templates/missions/mission_base.html

mentioned in #1599 and #1641, the footer on these pages was being styled
within the "container" div due to a missing closing tag. I think I've
tracked it down and corrected it. 
The following is what I currently see on the live site:
and with the change made in the PR I see the following:
and all seems well on the other training pages:
I think this fix is pretty straight forward; I've checked things on Firefox, Chrome and Safari but if someone could review it on their own machine as well that'd be great.

Fix footer alignment on missions pages

---

mysite/search/templates/search/search.html

Changed line 292 to call ".on" instead of ".one". This fixes a portion of issue #1595.
Regarding the position of the text, it seems that $.jGrowl is being used to display the information. jGrowl defaults only to only 5 different positions ( top-left, top-right, bottom-left, bottom-right, center), so I cannot currently edit the position of the box. However, I have fixed the issue where clicking the box only displays it once.
Also, I apologize about the previous deletion of the pull. I was attempting to rebase my branch to the openhatch-master, however along the way I deleted my original branch on github due to merging issues.

Fixed "What's This?" displaying only once

---

mysite/account/templates/account/login.html
mysite/account/templates/account/login_old.html
mysite/account/templates/account/login_openid.html

This is a fix for issue #451.
mysite/account/templates/account/login_old.html:
Change “Relatedly” to “Related”. It’s a good generic term for
describing things related to login.
mysite/account/templates/account/login_openid.html:
Change wording to imperative. This is clearer than previous wording.
Also, add link to “What is OpenID?” blog post as it makes more sense
next to have it here rather than off to the side.
mysite/account/templates/account/login.html:
Change wording to use OpenID. This is now consistent with other usage
elsewhere.
Also change “Relatedly” to “Related” for consistency.
James

Update wording for log in pages

---

mysite/base/templates/base/base.html
mysite/base/views.py
mysite/settings.py

For feature #1676 to aid in debugging and troubleshooting the live
site. Currently only visible on the home page.
This is mostly intended to drive the discussion on this feature, as a proof of concept. The commit hash and link is included only on the main page footer, I think ideally it'd be in the footer on every page but I think that is infeasible because of how the footer is rendered in the `base.html` template (and therefore not invoked in a single view function).
The link is to the commit itself in `oh-mainline` on Github and looks like the rest of the links:
In the event that the git command fails in any way, the `COMMIT_HASH` variable in `settings.py` will be empty/falsey and the template will render as it does today (and on every page that isn't Home):
I thought `settings.py` was …

Add commit hash to footer

---

mysite/static/css/account/settings.css

Fix for unexpected wrapping of jGrowl popup as mentioned in fix #1595.
The jGrowl popup which is created when clicking “What’s this?” next to
“bitesize” created a popup which was wrapping the message text after
every word. This was happening because the div message class was
inheriting “width: 0%” from .default div in settings.css.
This change fixes that by giving divs their own message class with
“width: 100%”.
The popup was also inheriting “background-color: #FF6D3D;” from the
.default div class, but you couldn’t see it (presumably) because width
was 0%.
This commit also fixes that and sets the background to the expected
#000 (black) color.

Fix jGrowl message wrapping inappropriately

---

mysite/account/templates/account/set_location.html

Tested on:
mac os x 10.9.2 mavericks in: 
* chrome 33.0.1750.152
* firefox 27.0.1
* safari 7.0.3 (9537.75.14)
Windows
* windows 8 chrome
* windows 7 chrome 33.0.1750.154
* windows 7 internet explorer 10.0.9200.16736
No errors in javascript consoles from any code added. Geolocation worked from 2 different cities.
Ran tests via manage.py 370 tests run, 52 skipped all OK, no failures.
The backend will still need to be updated as it contains the original reverse geocoding code. Issue 920 will still be reproducible if the geolocation database isn't found or if there is a location entered that is not recognized when run from a cloned repo. This code will continue working with the old backend as it is just passing one string through the post.

WIP do not merge - address front end problem of issue 920; geocoding in javascript

---

mysite/customs/forms.py
mysite/customs/tests.py

The first regex wasn't allowing dots in repository names, so many valid project URLs aren't accepted by http://openhatch.org/customs/add/github.

Fix github url regexes

---

README.rst

A minor typo fix to make coveralls not complain that our badge does not exist.

Fix spacing for coveralls badge

---

mysite/base/models.py

The static method ``key_for_model(cls)`` for the TimeStamp class is unused by oh-mainline. Removing code.
Related to #1711

Remove unused function from TimeStamp class

---

mysite/static/js/importer.js

This addresses: https://github.com/openhatch/oh-mainline/issues/1567.
The root cause for this problem was that the view `save_portfolio_entry_ordering_do` in `base/views.py` has the annotation `@login_required`, which requires a CSRF token to be passed.
In the absence of this token, the response status is a 403, which causes the cryptic `Merde: there was an error saving your ordering` to be displayed.

Add CSRF Token to Post Request for Reordering projects to prevent 403

---

mysite/profile/tests.py

For readability, revert the formatting of time calculations to the original format.
To be more explicit and pythonic, add the parens back on the returned tuple.

Make 2 format changes per ehashman suggestions on #1714

---

mysite/missions/templates/missions/diffpatch/hints.html
mysite/missions/templates/missions/git/checkout.html
mysite/missions/templates/missions/shell/cd.html
mysite/missions/templates/missions/shell/cp_mv.html
mysite/missions/templates/missions/shell/ls.html
mysite/missions/templates/missions/shell/mkdir_rm.html
mysite/missions/templates/missions/shell/resources.html
mysite/missions/templates/missions/shell/structure.html

Resolves https://github.com/openhatch/oh-mainline/issues/1754
"Present working directory" strikes me as pretty close to "print working
directory," which is only addressed in windows-setup in the missions. As
such, it seems perhaps clearer to just skip that terminology for now.
It may be better to use the `kbd` or `<kbd class="kbd">` style in some sections
where that's currently not the case; some sections do interesting stuff when
viewed in an editor with syntax highlighting (e.g. swapping formatting).
Still true with the e.g. `patch -pnum < patchfile.patch` line, since the less-than
caret can get flagged as half a `<tag>`.
Would be just as happy to swap all the bolded code/bash lines
out for `kbd` formatted stuff instead — there's more opportunity for it here
(though I'm not sure of the …

many clarity and punctuation fixes; rewrote some sections for clarity

---

vendor/packages/django-http-proxy/httpproxy/migrations/0001_initial.py

This was causing problem in migrations because Django's inbuilt migrations ( which was introduced in 1.7 ) was being used. 
Running
```
./manage.py schemamigration httpproxy --initial
```
converted them back to South migrations. 
#1734

convert django-http-proxy's Django migrations to South migrations

---

mysite/missions/templates/missions/shell/ls.html

https://openhatch.org/missions/shell/ls
feedback block is moved at the top of the page.
#1749 
Demo:
http://imgur.com/yb8dMh0
If this also needs to be fixed for other pages, then please let me know.

challenge feedback now visible in the top of the page

---

mysite/profile/templates/profile/base_profile.html

Bug : 'Edit Your Settings' option is being shown even if the user is not logged in. 
I have tested it locally and this PR will resolve the issue.

Fix for Issue#1785
